// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef MauiCore_VERSION_H
#define MauiCore_VERSION_H

#define MauiCore_VERSION_STRING "0.6.6"
#define MauiCore_VERSION_MAJOR 0
#define MauiCore_VERSION_MINOR 6
#define MauiCore_VERSION_PATCH 6
#define MauiCore_VERSION ((0<<16)|(6<<8)|(6))

#endif
