// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef MauiCoreAudio_VERSION_H
#define MauiCoreAudio_VERSION_H

#define MauiCoreAudio_VERSION_STRING "0.6.6"
#define MauiCoreAudio_VERSION_MAJOR 0
#define MauiCoreAudio_VERSION_MINOR 6
#define MauiCoreAudio_VERSION_PATCH 6
#define MauiCoreAudio_VERSION ((0<<16)|(6<<8)|(6))

#endif
