// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef MauiCoreNotifications_VERSION_H
#define MauiCoreNotifications_VERSION_H

#define MauiCoreNotifications_VERSION_STRING "0.6.6"
#define MauiCoreNotifications_VERSION_MAJOR 0
#define MauiCoreNotifications_VERSION_MINOR 6
#define MauiCoreNotifications_VERSION_PATCH 6
#define MauiCoreNotifications_VERSION ((0<<16)|(6<<8)|(6))

#endif
